services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    ports:
      - 3000:3000
    env_file:
      - .env.production
    restart: always
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:16.2
    ports:
      - '5432:5432'
    env_file:
      - .env.production
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
