services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    ports:
      - ${PORT}:3000
    env_file:
      - .env
    restart: on-failure
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgis/postgis:16-3.4
    ports:
      - ${DB_PORT}:5432
    env_file:
      - .env
    restart: on-failure

volumes:
  postgres-data:
