services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    ports:
      - 3000:3000
    env_file:
      - .env
    restart: on-failure
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgis/postgis:16-3.4
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: on-failure

volumes:
  postgres-data:
